from __future__ import annotations

from zoneinfo import ZoneInfo


PROJECT_NAME = "RN Opportunity Radar"
TIMEZONE_NAME = "America/Los_Angeles"
TIMEZONE = ZoneInfo(TIMEZONE_NAME)
REQUEST_TIMEOUT_SECONDS = 30
KEEP_EXPIRED_DAYS = 30
MAX_DESCRIPTION_CHARS = 2_400

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

SOURCE_URLS = {
    "ohsu_nursing": "https://www.ohsu.edu/human-resources/nursing-jobs-ohsu-oregon",
    "ohsu_rn": "https://www.ohsu.edu/human-resources/registered-nurse-jobs",
    "ohsu_health_jobs": "https://www.ohsu.edu/human-resources/all-health-care-jobs-ohsu",
    "providence_nursing": "https://providence.jobs/nursing/",
    "providence_oregon": "https://providence-oregon.jobs/",
    "providence_oregon_nursing": "https://providence-oregon.jobs/job-function/nursing/jobs/",
    "peacehealth_oregon_nursing": "https://www.peacehealth.org/job-opportunities/nursing-jobs/nursing-jobs-oregon",
    "peacehealth_nursing_search": "https://careers.peacehealth.org/search/nursing/jobs",
    "legacy_nursing": "https://www.legacyhealth.org/for-health-professionals/careers/nursing",
    "kaiser_northwest_nursing": "https://www.kaiserpermanentejobs.org/nursing-careers-northwest",
    "kaiser_portland_nursing": (
        "https://www.kaiserpermanentejobs.org/employment/"
        "portland-oregon-united-states-nursing-licensed-and-nurse-practitioners-jobs/"
        "641/8267760/6252001-5744337-5742126-5746545/4"
    ),
    "oregon_nurse_career_center": "https://jobs.oregonrn.org/",
    "ania_jobs": "https://jobs.ania.org/",
    "amia_jobs": "https://jobs.amia.org/",
    "ohsu_ai_center": "https://www.ohsu.edu/school-of-medicine/center-ai-enabled-learning-health-science",
    "ohsu_heal": (
        "https://www.ohsu.edu/school-of-medicine/"
        "medical-informatics-and-clinical-epidemiology/healthcare-ethical-ai-lab-heal"
    ),
    "ohsu_dice_job_descriptions": (
        "https://www.ohsu.edu/school-of-medicine/"
        "medical-informatics-and-clinical-epidemiology/job-descriptions"
    ),
    "ohsu_dice_career_resources": (
        "https://www.ohsu.edu/school-of-medicine/"
        "medical-informatics-and-clinical-epidemiology/career-resources"
    ),
    "providence_office_of_transformation": (
        "https://blog.providence.org/blog/office-of-transformation-helps-caregivers-better-help-you"
    ),
    "providence_cnp": "https://blog.providence.org/blog/new-providence-platform-helps-patients-get-answers-quickly",
    "providence_provaria": "https://blog.providence.org/blog/provaria-transforming-care-with-ai-patient-message-management",
    "providence_dax": "https://blog.providence.org/blog/dax-copilot-life-changing-technology",
    "pearl_health_careers": "https://www.pearlhealth.com/careers",
    "pearl_health_jobs": "https://jobs.ashbyhq.com/pearlhealth",
    "pearl_health_technology": "https://www.pearlhealth.com/technology",
    "viz_ai_careers": "https://www.viz.ai/careers",
    "viz_ai_jobs": "https://jobs.ashbyhq.com/Viz.ai",
    "viz_ai_platform": "https://www.viz.ai/vizai-one",
}

SOURCE_DEFINITIONS: dict[str, dict[str, object]] = {
    "ohsu_nursing": {
        "name": "OHSU Nursing Jobs",
        "kind": "job",
        "parser": "icims",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_nursing"],
        "search_url": "https://nursingcareers-ohsu.icims.com/jobs/search?ss=1&searchKeyword=nurse&in_iframe=1",
        "source_priority": 100,
        "source_context": "official Oregon nursing hiring page",
    },
    "ohsu_rn": {
        "name": "OHSU Registered Nurse Jobs",
        "kind": "job",
        "parser": "icims",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_rn"],
        "search_url": (
            "https://nursingcareers-ohsu.icims.com/jobs/search"
            "?ss=1&searchKeyword=registered+nurse&in_iframe=1"
        ),
        "source_priority": 100,
        "source_context": "official registered nurse jobs page",
    },
    "ohsu_health_jobs": {
        "name": "OHSU Health Care Jobs",
        "kind": "job",
        "parser": "icims",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_health_jobs"],
        "search_url": "https://nursingcareers-ohsu.icims.com/jobs/search?ss=1&searchKeyword=clinical&in_iframe=1",
        "source_priority": 95,
        "source_context": "official health jobs page for adjacent bridge-role discovery",
    },
    "providence_nursing": {
        "name": "Providence Nursing Careers",
        "kind": "job",
        "parser": "providence_api",
        "company": "Providence",
        "url": SOURCE_URLS["providence_nursing"],
        "api_url": "https://prod-search-api.jobsyn.org/api/v1/solr/search",
        "origin_host": "providence.jobs",
        "params": {"jobfunction": "nursing", "num_items": 50},
        "allowed_states": ["OR"],
        "source_priority": 96,
        "source_context": "official Providence nursing careers page",
    },
    "providence_oregon": {
        "name": "Providence Oregon Careers",
        "kind": "job",
        "parser": "providence_api",
        "company": "Providence",
        "url": SOURCE_URLS["providence_oregon"],
        "api_url": "https://prod-search-api.jobsyn.org/api/v1/solr/search",
        "origin_host": "providence-oregon.jobs",
        "params": {"jobfunction": "nursing", "num_items": 50},
        "source_priority": 100,
        "source_context": "official Providence Oregon careers page",
    },
    "providence_oregon_nursing": {
        "name": "Providence Oregon Nursing Jobs",
        "kind": "job",
        "parser": "providence_api",
        "company": "Providence",
        "url": SOURCE_URLS["providence_oregon_nursing"],
        "api_url": "https://prod-search-api.jobsyn.org/api/v1/solr/search",
        "origin_host": "providence-oregon.jobs",
        "params": {"jobfunction": "nursing", "num_items": 50},
        "source_priority": 100,
        "source_context": "official Providence Oregon nursing page",
    },
    "peacehealth_oregon_nursing": {
        "name": "PeaceHealth Oregon Nursing Jobs",
        "kind": "job",
        "parser": "peacehealth_jobs",
        "company": "PeaceHealth",
        "url": SOURCE_URLS["peacehealth_oregon_nursing"],
        "search_url": "https://careers.peacehealth.org/search/jobs/in/or-oregon?brand=nursing&cfml3=Nursing",
        "source_priority": 94,
        "source_context": "official Oregon nursing careers page",
    },
    "peacehealth_nursing_search": {
        "name": "PeaceHealth Nursing Search",
        "kind": "job",
        "parser": "peacehealth_jobs",
        "company": "PeaceHealth",
        "url": SOURCE_URLS["peacehealth_nursing_search"],
        "search_url": "https://careers.peacehealth.org/search/jobs?cfml3=Nursing&brand=nursing",
        "allowed_states": ["OR"],
        "max_pages": 4,
        "source_priority": 90,
        "source_context": "official PeaceHealth nursing search with Oregon filtering",
    },
    "legacy_nursing": {
        "name": "Legacy Nursing Careers",
        "kind": "job",
        "parser": "icims",
        "company": "Legacy Health",
        "url": SOURCE_URLS["legacy_nursing"],
        "search_url": (
            "https://nursing-lhs.icims.com/jobs/search"
            "?ss=1&searchRelation=keyword_all&searchKeyword=rn&mobile=false"
            "&width=1410&height=500&bga=true&needsRedirect=false"
            "&jan1offset=-480&jun1offset=-420&in_iframe=1"
        ),
        "source_priority": 98,
        "source_context": "official Legacy nursing careers page",
    },
    "kaiser_northwest_nursing": {
        "name": "Kaiser Northwest Nursing Careers",
        "kind": "job",
        "parser": "kaiser_search",
        "company": "Kaiser Permanente",
        "url": SOURCE_URLS["kaiser_northwest_nursing"],
        "search_url": SOURCE_URLS["kaiser_northwest_nursing"],
        "source_priority": 96,
        "source_context": "official Kaiser Northwest nursing careers page",
    },
    "kaiser_portland_nursing": {
        "name": "Kaiser Portland Nursing Jobs",
        "kind": "job",
        "parser": "kaiser_search",
        "company": "Kaiser Permanente",
        "url": SOURCE_URLS["kaiser_portland_nursing"],
        "search_url": SOURCE_URLS["kaiser_portland_nursing"],
        "source_priority": 100,
        "source_context": "official Portland nursing search page",
    },
    "oregon_nurse_career_center": {
        "name": "Oregon Nurse Career Center",
        "kind": "job",
        "parser": "board_results",
        "company": "Oregon Nurse Career Center",
        "url": SOURCE_URLS["oregon_nurse_career_center"],
        "results_url": "https://jobs.oregonrn.org/jobs/state/oregon/",
        "source_class": "board",
        "source_priority": 80,
        "source_context": "Oregon nursing board filtered to Oregon listings",
        "default_tags": ["Board", "Oregon"],
    },
    "ania_jobs": {
        "name": "ANIA Jobs Board",
        "kind": "job",
        "parser": "board_results",
        "company": "ANIA",
        "url": SOURCE_URLS["ania_jobs"],
        "results_url": "https://jobs.ania.org/jobseeker/search/results/",
        "source_class": "board",
        "source_priority": 76,
        "source_context": "specialty informatics board for bridge-role discovery",
        "default_tags": ["Board", "Informatics"],
    },
    "amia_jobs": {
        "name": "AMIA Jobs Board",
        "kind": "job",
        "parser": "board_results",
        "company": "AMIA",
        "url": SOURCE_URLS["amia_jobs"],
        "results_url": "https://jobs.amia.org/jobseeker/search/results/",
        "source_class": "board",
        "source_priority": 78,
        "source_context": "medical informatics board for bridge and watch opportunities",
        "default_tags": ["Board", "Informatics"],
    },
    "pearl_health_frontier_roles": {
        "name": "Pearl Health Frontier Roles",
        "kind": "job",
        "parser": "ashby_jobs",
        "company": "Pearl Health",
        "url": SOURCE_URLS["pearl_health_careers"],
        "board_url": SOURCE_URLS["pearl_health_jobs"],
        "track": "frontier_ecosystem",
        "subtrack": "vendor",
        "horizon": "stretch",
        "geo_scope": "remote_us",
        "rn_leverage_type": "clinical_success",
        "relocation_risk": "possible",
        "source_priority": 84,
        "source_context": "remote-friendly value-based care employer with customer success, product, operations, and clinical performance roles",
        "default_tags": ["Frontier", "Remote", "Value-Based Care"],
    },
    "viz_ai_frontier_roles": {
        "name": "Viz.ai Frontier Roles",
        "kind": "job",
        "parser": "ashby_jobs",
        "company": "Viz.ai",
        "url": SOURCE_URLS["viz_ai_careers"],
        "board_url": SOURCE_URLS["viz_ai_jobs"],
        "track": "frontier_ecosystem",
        "subtrack": "vendor",
        "horizon": "stretch",
        "geo_scope": "remote_us",
        "rn_leverage_type": "implementation",
        "relocation_risk": "none",
        "source_priority": 88,
        "source_context": "remote AI care-coordination employer with clinical pathway, workflow, and clinical specialist roles",
        "default_tags": ["Frontier", "Remote", "AI Care Coordination"],
    },
    "ohsu_ai_center": {
        "name": "OHSU AI Center",
        "kind": "signal",
        "parser": "signal_page",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_ai_center"],
        "track": "frontier_ecosystem",
        "subtrack": "research_innovation",
        "horizon": "stretch",
        "geo_scope": "oregon",
        "rn_leverage_type": "research",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "ai-enabled learning health science",
        "tags": ["AI", "Learning Health System", "Employer Signal"],
    },
    "ohsu_heal": {
        "name": "OHSU HEAL",
        "kind": "signal",
        "parser": "signal_page",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_heal"],
        "track": "frontier_ecosystem",
        "subtrack": "research_innovation",
        "horizon": "stretch",
        "geo_scope": "oregon",
        "rn_leverage_type": "research",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "ethical ai and clinical informatics",
        "tags": ["Ethical AI", "Clinical Informatics", "Employer Signal"],
    },
    "ohsu_dice_job_descriptions": {
        "name": "OHSU DICE Job Descriptions",
        "kind": "signal",
        "parser": "signal_page",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_dice_job_descriptions"],
        "track": "frontier_ecosystem",
        "subtrack": "research_innovation",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "informatics",
        "relocation_risk": "none",
        "source_priority": 96,
        "source_context": "informatics job descriptions and bridge-role map",
        "tags": ["Informatics", "Career Mapping", "Bridge Role"],
    },
    "ohsu_dice_career_resources": {
        "name": "OHSU DICE Career Resources",
        "kind": "signal",
        "parser": "signal_page",
        "company": "OHSU",
        "url": SOURCE_URLS["ohsu_dice_career_resources"],
        "track": "frontier_ecosystem",
        "subtrack": "research_innovation",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "informatics",
        "relocation_risk": "none",
        "source_priority": 96,
        "source_context": "career resources for medical informatics and clinical epidemiology",
        "tags": ["Career Resources", "Informatics", "Employer Signal"],
    },
    "providence_office_of_transformation": {
        "name": "Providence Office of Transformation",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Providence",
        "url": SOURCE_URLS["providence_office_of_transformation"],
        "track": "frontier_ecosystem",
        "subtrack": "health_system",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "implementation",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "office of transformation",
        "tags": ["Transformation", "Operations", "Employer Signal"],
    },
    "providence_cnp": {
        "name": "Providence Conversation & Navigation Platform",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Providence",
        "url": SOURCE_URLS["providence_cnp"],
        "track": "frontier_ecosystem",
        "subtrack": "health_system",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "clinical_success",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "conversation & navigation platform",
        "tags": ["Navigation", "Digital Care", "Employer Signal"],
    },
    "providence_provaria": {
        "name": "Providence Provaria",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Providence",
        "url": SOURCE_URLS["providence_provaria"],
        "track": "frontier_ecosystem",
        "subtrack": "health_system",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "implementation",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "provaria and AI patient message management",
        "tags": ["AI Workflow", "Messaging", "Employer Signal"],
    },
    "providence_dax": {
        "name": "Providence DAX Copilot",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Providence",
        "url": SOURCE_URLS["providence_dax"],
        "track": "frontier_ecosystem",
        "subtrack": "health_system",
        "horizon": "post_reinstatement",
        "geo_scope": "oregon",
        "rn_leverage_type": "informatics",
        "relocation_risk": "none",
        "source_priority": 100,
        "source_context": "dax copilot ambient documentation",
        "tags": ["Ambient Documentation", "AI", "Employer Signal"],
    },
    "pearl_health_platform_signal": {
        "name": "Pearl Health Technology",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Pearl Health",
        "url": SOURCE_URLS["pearl_health_technology"],
        "track": "frontier_ecosystem",
        "subtrack": "venture_signal",
        "horizon": "stretch",
        "geo_scope": "remote_us",
        "rn_leverage_type": "product_clinical",
        "relocation_risk": "possible",
        "source_priority": 82,
        "source_context": "value-based care technology platform with clinical performance and provider workflow focus",
        "tags": ["Vendor Signal", "Clinical Operations", "Value-Based Care"],
    },
    "viz_ai_platform_signal": {
        "name": "Viz.ai Platform Signal",
        "kind": "signal",
        "parser": "signal_page",
        "company": "Viz.ai",
        "url": SOURCE_URLS["viz_ai_platform"],
        "track": "frontier_ecosystem",
        "subtrack": "venture_signal",
        "horizon": "stretch",
        "geo_scope": "remote_us",
        "rn_leverage_type": "implementation",
        "relocation_risk": "possible",
        "source_priority": 86,
        "source_context": "AI-powered intelligent care coordination and clinical workflow platform",
        "tags": ["Vendor Signal", "AI Care Coordination", "Clinical Workflow"],
    },
}

STRONG_RN_TITLE_SIGNALS = {
    "registered nurse": 70,
    "rn ": 58,
    "rn-": 58,
    "icu rn": 72,
    "critical care rn": 72,
    "emergency department rn": 60,
    "operating room rn": 55,
    "rn coordinator": 52,
    "rn case manager": 58,
    "clinic rn": 46,
    "care manager rn": 58,
}

BRIDGE_TITLE_SIGNALS = {
    "clinical informatics": 68,
    "nursing informatics": 78,
    "informatics analyst": 52,
    "epic analyst": 50,
    "ehr analyst": 46,
    "clinical systems": 44,
    "clinical documentation": 38,
    "implementation specialist": 42,
    "clinical solution specialist": 48,
    "quality improvement": 36,
    "quality facilitator": 34,
    "virtual care": 38,
    "virtual nursing": 44,
    "digital health": 42,
    "clinical research": 28,
    "research assistant": 18,
    "research coordinator": 28,
    "population health": 24,
    "utilization management": 26,
}

DESCRIPTION_SIGNALS = {
    "epic": 18,
    "electronic health record": 20,
    "ehr": 18,
    "informatics": 24,
    "workflow": 14,
    "implementation": 14,
    "clinical systems": 18,
    "clinical documentation": 16,
    "quality improvement": 14,
    "data": 10,
    "analytics": 12,
    "ai": 20,
    "artificial intelligence": 26,
    "machine learning": 20,
    "ambient documentation": 18,
    "decision support": 16,
    "digital care": 14,
    "virtual care": 18,
    "care navigation": 12,
    "research": 10,
}

EMPLOYER_SIGNAL_BOOSTS = {
    "ohsu": 20,
    "providence": 20,
    "peacehealth": 8,
    "legacy": 8,
    "kaiser": 10,
}

SOURCE_CONTEXT_SIGNALS = {
    "ai-enabled learning health system": 30,
    "ai-enabled learning health science": 30,
    "ethical ai": 24,
    "office of transformation": 22,
    "conversation & navigation platform": 18,
    "provaria": 18,
    "dax copilot": 18,
    "career resources": 8,
    "job descriptions": 8,
}

PRIORITY_LOCATIONS = {
    "eugene, or": 28,
    "springfield, or": 28,
    "portland, or": 24,
    "salem, or": 16,
    "remote, or": 26,
    "oregon": 14,
}

SECONDARY_LOCATIONS = {
    "vancouver, wa": 10,
    "remote": 8,
    "pacific northwest": 8,
}

RN_REQUIREMENT_SIGNALS = {
    "rn required": 34,
    "rn preferred": 18,
    "current rn license": 30,
    "oregon rn license": 34,
    "registered nurse license": 28,
    "registered nurse preferred": 18,
    "bsn preferred": 8,
    "critical care experience": 10,
    "icu experience": 12,
}

NEGATIVE_TITLE_SIGNALS = {
    "cna": -55,
    "lpn": -45,
    "medical assistant": -60,
    "physician": -50,
    "resident physician": -65,
    "pharmacist": -35,
    "dentist": -70,
    "therapist": -26,
    "director": -38,
    "vice president": -60,
    "chief": -60,
    "recruiter": -55,
    "faculty": -18,
    "student": -40,
    "intern": -48,
    "sales": -45,
    "account executive": -55,
    "travel nurse": -18,
}

NEGATIVE_DESCRIPTION_SIGNALS = {
    "certified nursing assistant": -50,
    "medical assistant": -55,
    "physician only": -50,
    "no rn required": -70,
    "commission": -30,
}

ICU_SIGNALS = {
    "icu": 12,
    "critical care": 14,
    "intensive care": 14,
    "rapid response": 8,
    "perioperative": 8,
    "surgery": 8,
    "acuity": 6,
}

BUCKET_THRESHOLDS = {
    "priority": 90,
    "bridge": 68,
    "watch": 44,
    "long_shot": 28,
    "discard": 27,
}

AI_FORWARD_EMPLOYERS = {"ohsu", "providence"}
OREGON_EMPLOYERS = {"ohsu", "providence", "peacehealth", "legacy", "kaiser"}
